// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace FullStackTest.Data.Models;

public partial class MovieDBContext : DbContext
{
    public MovieDBContext(DbContextOptions<MovieDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Movie> Movie { get; set; }

    public virtual DbSet<Review> Review { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Movie>(entity =>
        {
            entity.HasKey(e => e.MovieId).HasName("PK__Movie__4BD2943AE3E377F5");

            entity.Property(e => e.MovieId).HasColumnName("MovieID");
            entity.Property(e => e.CreationDate).HasColumnType("date");
            entity.Property(e => e.Description).HasMaxLength(300);
            entity.Property(e => e.Enable).HasDefaultValueSql("((1))");
            entity.Property(e => e.Name).HasMaxLength(100);
            entity.Property(e => e.UpdateDate).HasColumnType("date");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Review__74BC79CE955EABAA");

            entity.Property(e => e.CreationDate).HasColumnType("date");
            entity.Property(e => e.Review1)
                .HasMaxLength(500)
                .HasColumnName("Review");
            entity.Property(e => e.UpdateDate).HasColumnType("date");

            entity.HasOne(d => d.Movie).WithMany(p => p.Review)
                .HasForeignKey(d => d.MovieId)
                .HasConstraintName("FK__Review__MovieId__2C3393D0");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}