// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace FullStackTest.Data.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public bool? Enable { get; set; }

    public DateTime? CreationDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public virtual ICollection<Review> Review { get; } = new List<Review>();
}